### PR TITLE
Add copy files feature

### PR DESCRIPTION
**Pull request by degzcs**
add a new deployment method, which copy the js, css and html files from lineman application dist folder to a rails public folder.

### CODE REVIEW

**Comment by searls** [comment]
Interesting!

**Comment by searls** [comment]
Why close the PR?

**Comment by degzcs** [comment]
Hi, I'm fixing some issues here and then I will make the PR again. :D

**Comment by degzcs** [comment]
Hi, I made the PR again [here](https://github.com/linemanjs/rails-lineman/pull/15) ... please, let me know your thoughts.

**Pull request closed without merging**
