### PR TITLE
Add copy files feature

### PR DESCRIPTION
**Pull request by degzcs**
add a new deployment method, which copy the js, css and html files from lineman application dist folder to a rails public folder.

### CODE REVIEW

**Comment by searls** [comment]
Would you mind explaining who needs this PR? I have a few questions about your intent.
- Who uses the public directory in lieu of the asset pipeline? I've seen a lot of Rails projects, including some modern ones that disable the asset pipeline, but none that dump files into public/
- How does this differ from `cp -r`?

**Comment by degzcs** [comment]
The main reason is decoupling the frontend and the backend in the simplest way possible. Yes, this modification only copies the generated files (dist) to the public folder, not utilizing the asset pipeline when you already have done all precompilation using grunt tasks in lineman itself. The generation tasks in the remote server (installing node, lineman and its dependencies) when deploying is the part that I found useful. The added feature is to only free the developer from running a cp -R... yes.

What I could do is to rename the config option from "deploy_method'" to "deploy target" as this:

``` ruby
deploy_target = :asset_pipeline # Symbol: rails-lineman deployment still would work as usual, no changes there
deploy_target  = "public" # String: the path to copy everything into, after being generated by Lineman
```

Maybe this is a clearer configuration option naming, and if you wanted, you could also do:

``` ruby
deploy_target  = "public/app" # to copy "dist" into "app"
```

Later on you could "mount" multiple client side apps, but that would be another thing.

The alternative deploy method I propose is suitable when all HTML, Coffee, Sass and other source files are all together (not having any pages on Rails), without the need for Rails to provide anything (except for maybe, a JSON API for the app to communicate to, which is what I try to accomplish).

I am actually writing a blog post about this which I hope will be useful to understand why I propose this deployment method.

**Comment by searls** [comment]
I currently don't find the requirement compelling enough to merge in, but I'm open to hearing more (especially if others would find it useful). One person on our team has suggested that what you need is different enough that you should fork the gem and implement your own as `rails-lineman-public`, free of the baggage of all the asset goop this gem does. Another person suggested that changing the `dist` directory in your lineman project might be all you need to do to force it to write into Rails' `public/..`

**Comment by searls** [comment]
Separately, I have three pieces of meta-feedback about this PR:
1. When a PR doesn't solve a clearly understood problem shared by most or all users, that makes me more cautious about merging it in. If the PR is going to introduce a significant new logical branch of behavior (as this one does, it basically splits the gem into two modes of operation), then there is a pretty high burden of proof that the feature should be included. When I first started maintaining open source projects, I eagerly merged branches for non-default ("branched") features because if I wasn't personally using them, they couldn't harm current users. What I learned over time was two things: (1) every branch is another vector to test for in all future changes, and (2) if the original author stops using their own branched feature, I might find myself spending hours on my nights and weekends to maintain a feature that has literally zero users.
2. This PR came out of the blue—it wasn't tied to an issue, we didn't discuss it in advance, and it didn't have a clear description when it was sent.  As a result, I had no opportunity to express my concerns outlined above to you. Now that we're here, this won't feel very fair to you, because you spent a bunch of time working on it. This isn't fair to me, because now I feel like a jerk for writing this and suggesting you wasted your time (you did not! You can always deploy your fork and if it solves your problem, then great).
3. This PR's changes are broader-based than what is described. In addition to adding this feature, the branch:
   - bumps the patch version (which presumes control of the gem's versioning and releasing)
   - adds yourself as the second gem author (which presumes I'm comfortable with that level of attribution)
   - it touches up unrelated parts of the README
   - it changes the code's style in at least one place that I disagree with; meaning that were I to merge it in, I'd first feel the need to go through and clean up the stylistic and minor design changes introduced

Please don't find my words harsh or judgmental. I've been on the opposite side of this pull request a dozen times, and I'm sure I will be again. If I've learned one thing, though, is that it's more effective to initially invest my time communicating to build consensus than to submit (albeit excellent) code to someone who's not expecting it.

**Comment by degzcs** [comment]
sorry for all the trouble, I actually agree with everything you said and totally understand the situation now. Its fine by me to use a fork or build a new gem since our approaches are different. Thanks for the tips! :+1:

**Comment by jasonkarns** [comment]
@degzcs I've actually had similar scenarios in the past and we added a `grunt-contrib-copy` task to the end of our lineman `build` phase to copy the appropriate files from `./dist` to `../public`.

I think this could make an excellent lineman plugin and would be much smaller. (And also useful outside of rails)

**Comment by darrencauthon** [comment]
@searls :

> This PR came out of the blue—it wasn't tied to an issue, we didn't discuss it in advance, and it didn't have a clear description when it was sent. As a result, I had no opportunity to express my concerns outlined above to you.
> This isn't fair to me, because now I feel like a jerk for writing this and suggesting you wasted your time (you did not! You can always deploy your fork and if it solves your problem, then great).
> searls referenced this pull request in testdouble/double-takes 15 hours ago
> Open
> post idea: Pull Request ettiquette #29

I don't know either of you, but I've been thinking about this PR.  I feel it's been unnecessarily negative by @searls trying **not** to be negative, and it's the type of response that stifles devs in the future.

Side story, one of my first PRs to a public project was a full refactor to a project with junk code.  I started to use the project, liked it, but the code was an absolute disaster.  I was new to working with others on Github, but I knew how to refactor and test code... so I did.  I popped in 20-30 tests, refactored the bits, added the projects first tests, and in most ways made the project a "better" project.  But surprisingly to me, they didn't accept it!  

I didn't take offense, they didn't take offense, it was just a "no."  But in the process most of my "code shyness" went away, and I've been popping PRs against other projects since.  I've learned that people don't want big shake-ups in PRs, and it's better to follow their advice, not touch versioning... all the basics that devs can only learn by doing. 

And **doing** is **awesome**.  I agree with the technical reasons that @searls rejected the PR, but I think @degzcs has put himself in a higher tier of developer by submitting it.   And it's good stuff, too!  This is very thorough code, updating tests, documentation, adding a rake task... @degzcs has made something that solves a problem, is worthwhile as a fork, and **works**, and the changes were organized.  Great work... that just doesn't fit the goals of the project.  

My advice to @degzcs is to keep it up!  Don't be afraid to pop a PR against any Github project, and don't take offense if anybody says no!  Hey, getting a **NO** is a better response than you'll get on most projects, which is **SILENCE**. :smile:

My advice to @searls :  Chill out. :smile: It's just a PR.  Just saying "No Thanks" if enough.  Explaining in detail why you won't accept it and offering advice is awesome!  Pointing at this as if it were a breach in etiquette, posting on Twitter, telling him that he needed to talk to you first, and saying the very submission of the PR is "not fair to you"... I think that's going too far, and it's counter to the "spirit" of Github and OSS.  You're handling something that's very delicate... you don't want to accidentally blow the fire out. :fire:

**Comment by trek** [comment]
>  Just saying "No Thanks" is enough.

As a long time open source contributor and maintainer on several large projects, I can assure you that for some people a simple "no thanks" is not enough. I've been approached by people who have harbored secret grudges for years because their PRs are "never accepted" to projects I work on and they couldn't make sense of why.

One time someone was brought to tears over it.

**Pull request closed without merging**
